In [ ]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.7.1+cu118


## What is a Tensor ? 
### creating Tenssor
PyTorch Tensor are created using `torch.tensor` from : https://docs.pytorch.org/docs/stable/generated/torch.tensor.html#torch.tensor

In [5]:
#Scaler 
scaler=torch.tensor(7)
scaler.dtype

torch.int64

In [6]:
scaler.ndim

0

In [8]:
#Get tenosr as python int
scaler.item()

7

In [23]:
# Vector
vector = torch.tensor([7,1])
vector

tensor([7, 1])

In [24]:
#num of [] in the tensor
vector.ndim


1

In [25]:
#normal shapes like 1x2 , 3x1 for vector
vector.shape

torch.Size([2])

In [29]:
# MATRIX
MATRIX = torch.tensor([[7,8] , [6 , 5]] )
MATRIX

tensor([[7, 8],
        [6, 5]])

In [30]:
MATRIX.ndim

2

In [17]:
MATRIX.shape

torch.Size([2, 2])

In [31]:
MATRIX[0]

tensor([7, 8])

In [32]:
MATRIX[1]

tensor([6, 5])

In [34]:
# TENSOR
TENSOR=torch.tensor([[[1,2,3,4],[2,3,4,5] , [1,2,4,5]]])
TENSOR

tensor([[[1, 2, 3, 4],
         [2, 3, 4, 5],
         [1, 2, 4, 5]]])

In [35]:
TENSOR.ndim

3

In [36]:
TENSOR.shape

torch.Size([1, 3, 4])

In [37]:
TENSOR[0]

tensor([[1, 2, 3, 4],
        [2, 3, 4, 5],
        [1, 2, 4, 5]])

In [41]:
T=torch.tensor([[[0,0,0],[1,1,1],[2,2,2]] ,[[3,3,3] ,[4,4,4] ,[5,5,5]] , 
                [[6,6,6],[7,7,7] , [8,8,8]]])
T

tensor([[[0, 0, 0],
         [1, 1, 1],
         [2, 2, 2]],

        [[3, 3, 3],
         [4, 4, 4],
         [5, 5, 5]],

        [[6, 6, 6],
         [7, 7, 7],
         [8, 8, 8]]])

In [ ]:
T.shape #like an RGB each channel has a 3x3 matrix  


torch.Size([3, 3, 3])

## Random tensors

why random tensors?

Random tensors is important because many nn start from nueral networks and start struct something from these randoms numbers like diffusion models or gans 

we can do it my `torch.rand` : https://docs.pytorch.org/docs/stable/generated/torch.rand.html#torch.rand

In [47]:
#create a random tensor of size (3,4)
random_tensor= torch.rand(1,3,4)
random_tensor

tensor([[[0.4275, 0.2611, 0.2562, 0.2300],
         [0.4050, 0.3415, 0.0669, 0.2225],
         [0.9731, 0.4032, 0.1257, 0.4860]]])

In [48]:
random_tensor.ndim

3

In [49]:
# create random tenosr with a shape  of (3,244,244) similar to an image
random_image_size_tensor=torch.rand(size =(3,244,244))
random_image_size_tensor.shape , random_image_size_tensor.ndim

(torch.Size([3, 244, 244]), 3)

## Zeros and Ones

In [50]:
#create a tensor of all zeors 
zeros=torch.zeros(size=(3,4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [51]:
zeros*random_tensor

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [55]:
#create a tensor of all ones
ones=torch.ones(size=(3,4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [56]:
ones.dtype

torch.float32

In [58]:
random_tensor.dtype

torch.float32

## creating a range of tenosrs and tensors-like
for a range `torch.arange(start ,end ,step)`: https://docs.pytorch.org/docs/stable/generated/torch.arange.html#torch.arange


In [ ]:
#use torch.arange()
one_to_ten = torch.arange(start=1 , end=11 , step=1)
one_to_ten

tensor([  1,  78, 155, 232, 309, 386, 463, 540, 617, 694, 771, 848, 925])

In [68]:
#creatign tenosr like 
ten_zeros =torch.zeros_like(one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

## Tensor datatypes 
More about precision: https://en.wikipedia.org/wiki/Precision_(computer_science)

dtype : https://docs.pytorch.org/docs/stable/tensor_attributes.html#torch.dtype

**Note:** Tenosr datatypes is one of the 3 big erros you'll run into with PyTorch
1. Tenosrs not right datatype
2. Tenosrs not the right shape 
3. Tenosrs not on the right device   


In [ ]:
#float 32 tensor 
float_32_tensor= torch.tensor([.3,.4,.6] , dtype=None #data type for the tensor like float32 , float 16  do with precision and computing  
                              , device='cuda' ,  #where is the opperation will happned gpu or cpu 
                              requires_grad=False ) # track of the gradients with tensor opperations   
float_32_tensor

tensor([0.3000, 0.4000, 0.6000], device='cuda:0')

In [74]:
float_32_tensor.dtype

torch.float32

In [78]:
float_16_tenosr = float_32_tensor.type(torch.float16)

In [79]:
float_16_tenosr

tensor([0.3000, 0.3999, 0.6001], device='cuda:0', dtype=torch.float16)

In [81]:
float_16_tenosr * float_32_tensor #No error ? 

tensor([0.0900, 0.1600, 0.3601], device='cuda:0')

In [85]:
int_32_tenosr = torch.tensor([3,4,5] , dtype=torch.int32 , device='cuda')

In [ ]:
int_32_tenosr * float_32_tensor # No error ? 

tensor([0.9000, 1.6000, 3.0000], device='cuda:0')